name: reward_env
channels:
- nvidia
- conda-forge
dependencies:
- python
- wandb==0.15.0
- hydra-core==1.3.2
- pip
- pip:
  - sbx-rl
  - plotly
  - joblib
  - numpy
  - POT
  - scikit_learn
  - stable_baselines3
  - torch
  - tensorboard
  - moviepy
  - mujoco==3.1.4
  - gymnasium[classic-control]
  - jax[cuda12]==0.4.26
  - flake8
  - black
  - pylint
- cuda-nvcc

